import * as stylex from "@stylexjs/stylex";
import { tokens } from "../lib/tokens.stylex";

export const popupStyles = stylex.create({
  popup: {
    boxSizing: "border-box",
    width: 360,
    paddingTop: 14,
    paddingBottom: 14,
    paddingLeft: 16,
    paddingRight: 16,
    backgroundColor: tokens["--xb-surface"],
    color: tokens["--xb-ink"],
  },
  region: {
    position: "relative",
  },
  popupMain: {
    display: "flex",
    flexDirection: "column",
  },
  regionBorder: {
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: tokens["--xb-border"],
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 12,
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  brandMark: {
    display: "grid",
    placeItems: "center",
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "auto",
    width: 22,
    height: 22,
    borderRadius: 8,
    backgroundColor: "oklch(0.63 0.16 246 / 0.12)",
    color: tokens["--xb-primary"],
  },
  title: {
    margin: 0,
    fontSize: 15,
    lineHeight: 1.2,
    fontWeight: 700,
    color: tokens["--xb-ink"],
  },
  status: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    color: tokens["--xb-ink-muted"],
    fontSize: 12,
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
  statusDot: {
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "auto",
    width: 6,
    height: 6,
    borderRadius: "50%",
    backgroundColor: tokens["--xb-success"],
  },
  statStrip: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    alignItems: "center",
    minHeight: 64,
    paddingTop: 10,
    paddingBottom: 10,
  },
  statCell: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingLeft: 4,
    paddingRight: 4,
    borderLeftWidth: 1,
    borderLeftStyle: "solid",
    borderLeftColor: tokens["--xb-border"],
  },
  statCellFirst: {
    borderLeftStyle: "none",
  },
  statValue: {
    fontSize: 26,
    lineHeight: 1,
    fontWeight: 700,
    color: tokens["--xb-ink"],
    fontVariantNumeric: "tabular-nums",
  },
  statTick: {
    width: 20,
    height: 2,
    borderRadius: 1,
  },
  statTickDanger: {
    backgroundColor: tokens["--xb-danger"],
  },
  statTickWarning: {
    backgroundColor: tokens["--xb-warning"],
  },
  statTickSuccess: {
    backgroundColor: tokens["--xb-success"],
  },
  statLabel: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: tokens["--xb-ink-muted"],
  },
  toggles: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    paddingTop: 12,
    paddingBottom: 12,
  },
  toggleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    cursor: "pointer",
  },
  toggleCopy: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
  },
  toggleTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: tokens["--xb-ink"],
  },
  toggleCaption: {
    fontSize: 11,
    fontWeight: 500,
    color: tokens["--xb-ink-muted"],
  },
  switchInput: {
    appearance: "none",
    position: "relative",
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "auto",
    width: 36,
    height: 20,
    margin: 0,
    borderRadius: 999,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens["--xb-border"],
    backgroundColor: tokens["--xb-track"],
    cursor: "pointer",
    transitionProperty: "background-color, border-color",
    transitionDuration: "160ms",
    transitionTimingFunction: tokens["--xb-ease-out"],
    outline: {
      ":focus-visible": `2px solid ${tokens["--xb-primary"]}`,
    },
    outlineOffset: {
      ":focus-visible": 2,
    },
  },
  syncRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingTop: 12,
    paddingBottom: 12,
  },
  syncLeft: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  telltale: {
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "auto",
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  telltaleSynced: {
    backgroundColor: tokens["--xb-success"],
  },
  telltalePending: {
    backgroundColor: tokens["--xb-warning"],
  },
  telltaleError: {
    backgroundColor: tokens["--xb-danger"],
  },
  syncCopy: {
    display: "flex",
    flexDirection: "column",
    gap: 1,
    minWidth: 0,
  },
  syncTitle: {
    fontSize: 12,
    fontWeight: 600,
    color: tokens["--xb-ink"],
  },
  syncDetail: {
    fontSize: 11,
    fontWeight: 500,
    color: tokens["--xb-ink-muted"],
  },
  footerChevron: {
    color: tokens["--xb-ink-muted"],
    fontSize: 15,
    lineHeight: 1,
  },
  syncAction: {
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "auto",
  },
  syncButton: {
    height: 28,
    minWidth: 72,
    paddingLeft: 10,
    paddingRight: 10,
    fontSize: 12,
    fontWeight: 600,
    borderRadius: 6,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens["--xb-border"],
    backgroundColor: tokens["--xb-surface"],
    color: tokens["--xb-ink"],
    cursor: "pointer",
    outline: {
      ":focus-visible": `2px solid ${tokens["--xb-primary"]}`,
    },
    outlineOffset: {
      ":focus-visible": 2,
    },
  },
  ghostLink: {
    borderStyle: "none",
    backgroundColor: "transparent",
    color: tokens["--xb-primary"],
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    padding: 0,
  },
  syncNote: {
    fontSize: 11,
    fontWeight: 500,
    color: tokens["--xb-ink-muted"],
  },
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 12,
  },
  footerActions: {
    display: "flex",
    gap: 8,
  },
  footerButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    height: 30,
    paddingLeft: 10,
    paddingRight: 10,
    fontSize: 12,
    fontWeight: 600,
    borderRadius: 6,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens["--xb-border"],
    backgroundColor: tokens["--xb-surface"],
    color: tokens["--xb-ink"],
    cursor: "pointer",
    outline: {
      ":focus-visible": `2px solid ${tokens["--xb-primary"]}`,
    },
    outlineOffset: {
      ":focus-visible": 2,
    },
  },
});
