import * as stylex from "@stylexjs/stylex";
import { tokens } from "../lib/tokens.stylex";

export const optionsShellStyles = stylex.create({
  root: {
    display: "grid",
    gridTemplateColumns: "232px 1fr",
    minHeight: "100vh",
    backgroundColor: tokens["--xb-surface"],
    color: tokens["--xb-ink"],
  },
  rail: {
    position: "sticky",
    top: 0,
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    backgroundColor: tokens["--xb-elevated"],
    borderRightWidth: 1,
    borderRightStyle: "solid",
    borderRightColor: tokens["--xb-border"],
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    height: 56,
    paddingLeft: 16,
    paddingRight: 16,
    flexShrink: 0,
    flexGrow: 0,
    flexBasis: "auto",
  },
  brandMark: {
    display: "grid",
    placeItems: "center",
    width: 22,
    height: 22,
    borderRadius: 8,
    backgroundColor: "oklch(0.63 0.16 246 / 0.12)",
    color: tokens["--xb-primary"],
  },
  brandName: {
    fontSize: 15,
    fontWeight: 700,
    lineHeight: 1.2,
  },
  nav: {
    display: "flex",
    flexDirection: "column",
    paddingTop: 4,
    paddingBottom: 4,
    paddingLeft: 8,
    paddingRight: 8,
    gap: 2,
  },
  navItem: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    gap: 10,
    height: 40,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 10,
    color: {
      default: tokens["--xb-ink-muted"],
      ":hover": tokens["--xb-ink"],
    },
    backgroundColor: {
      default: "transparent",
      ":hover": tokens["--xb-track"],
    },
    textDecoration: "none",
    fontSize: 13,
    fontWeight: 600,
    transitionProperty: "background-color, color",
    transitionDuration: "150ms",
    transitionTimingFunction: "ease",
    outline: {
      ":focus-visible": `2px solid ${tokens["--xb-primary"]}`,
    },
    outlineOffset: {
      ":focus-visible": 2,
    },
  },
  navItemActive: {
    backgroundColor: "oklch(0.63 0.16 246 / 0.12)",
    color: tokens["--xb-primary-text"],
  },
  version: {
    marginTop: "auto",
    paddingTop: 12,
    paddingLeft: 16,
    paddingRight: 16,
    paddingBottom: 16,
    fontSize: 11,
    fontWeight: 500,
    fontVariantNumeric: "tabular-nums",
    color: tokens["--xb-ink-muted"],
  },
  content: {
    minWidth: 0,
    padding: 40,
  },
  empty: {
    display: "grid",
    placeItems: "center",
    gap: 4,
    paddingTop: 48,
    paddingBottom: 48,
    paddingLeft: 16,
    paddingRight: 16,
    textAlign: "center",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens["--xb-border"],
    borderRadius: 16,
    backgroundColor: tokens["--xb-elevated"],
  },
  linkRow: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    color: tokens["--xb-primary"],
    fontSize: 13,
    fontWeight: 600,
    textDecoration: "none",
    outline: {
      ":focus-visible": `2px solid ${tokens["--xb-primary"]}`,
    },
    outlineOffset: {
      ":focus-visible": 2,
    },
  },
  paneHeader: {
    marginBottom: 24,
  },
  paneHeaderH1: {
    margin: 0,
    marginBottom: 4,
    fontSize: 20,
    fontWeight: 700,
    lineHeight: 1.25,
  },
  paneHeaderP: {
    margin: 0,
    fontSize: 13,
    fontWeight: 500,
    color: tokens["--xb-ink-muted"],
  },
  paneForm: {
    maxWidth: 640,
  },
  card: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens["--xb-border"],
    borderRadius: 16,
    backgroundColor: tokens["--xb-elevated"],
    overflow: "hidden",
  },
  cardNext: {
    marginTop: 20,
  },
  cardDanger: {
    borderColor: "oklch(0.601 0.212 21 / 0.35)",
  },
  cardHeader: {
    paddingTop: 16,
    paddingLeft: 20,
    paddingRight: 20,
    paddingBottom: 0,
  },
  cardHeaderH2: {
    margin: 0,
    marginBottom: 2,
    fontSize: 15,
    fontWeight: 700,
  },
  cardHeaderH2Danger: {
    color: tokens["--xb-danger"],
  },
  cardHeaderP: {
    margin: 0,
    marginBottom: 12,
    fontSize: 12,
    fontWeight: 500,
    color: tokens["--xb-ink-muted"],
  },
  row: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    minHeight: 56,
    paddingLeft: 20,
    paddingRight: 20,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens["--xb-border"],
  },
  rowLast: {
    borderBottomStyle: "none",
  },
  rowMeta: {
    minHeight: 44,
  },
  rowCopy: {
    display: "grid",
    gap: 2,
    minWidth: 0,
  },
  rowTitle: {
    fontSize: 13,
    fontWeight: 600,
  },
  rowCaption: {
    fontSize: 11,
    fontWeight: 500,
    color: tokens["--xb-ink-muted"],
  },
  rowValue: {
    fontSize: 12,
    fontWeight: 600,
    color: tokens["--xb-ink"],
    whiteSpace: "nowrap",
  },
  switchInput: {
    appearance: "none",
    position: "relative",
    flexShrink: 0,
    flexGrow: 0,
    flexBasis: "auto",
    width: 42,
    height: 24,
    margin: 0,
    borderRadius: 999,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens["--xb-border"],
    backgroundColor: tokens["--xb-track"],
    cursor: "pointer",
    transitionProperty: "background-color, border-color",
    transitionDuration: "160ms",
    transitionTimingFunction: tokens["--xb-ease-out"],
    outline: {
      ":focus-visible": `2px solid ${tokens["--xb-primary"]}`,
    },
    outlineOffset: {
      ":focus-visible": 2,
    },
  },
  sliderRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  slider: {
    width: 220,
    accentColor: tokens["--xb-primary"],
    outline: {
      ":focus-visible": `2px solid ${tokens["--xb-primary"]}`,
    },
    outlineOffset: {
      ":focus-visible": 2,
    },
  },
  numberInput: {
    boxSizing: "border-box",
    width: 56,
    height: 32,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens["--xb-border"],
    borderRadius: 8,
    backgroundColor: tokens["--xb-surface"],
    color: tokens["--xb-ink"],
    paddingLeft: 8,
    paddingRight: 8,
    fontSize: 13,
    fontVariantNumeric: "tabular-nums",
    textAlign: "right",
    outline: {
      ":focus-visible": `2px solid ${tokens["--xb-primary"]}`,
    },
    outlineOffset: {
      ":focus-visible": 2,
    },
  },
  aboutMark: {
    display: "grid",
    placeItems: "center",
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "oklch(0.63 0.16 246 / 0.12)",
    color: tokens["--xb-primary"],
    marginBottom: 12,
  },
  aboutVersion: {
    margin: 0,
    marginBottom: 12,
    fontSize: 13,
    fontWeight: 500,
    fontVariantNumeric: "tabular-nums",
    color: tokens["--xb-ink-muted"],
  },
  aboutTagline: {
    margin: 0,
    marginBottom: 16,
    maxWidth: "46ch",
    fontSize: 13,
    fontWeight: 500,
    lineHeight: 1.5,
    color: tokens["--xb-ink"],
  },
  dangerBody: {
    paddingLeft: 20,
    paddingRight: 20,
    paddingBottom: 16,
    fontSize: 12,
    fontWeight: 500,
    color: tokens["--xb-ink-muted"],
  },
  dangerActions: {
    paddingLeft: 20,
    paddingRight: 20,
    paddingBottom: 20,
  },
  wipePanel: {
    overflow: "hidden",
    maxHeight: 0,
    opacity: 0,
    transitionProperty: "max-height, opacity",
    transitionDuration: "200ms",
    transitionTimingFunction: tokens["--xb-ease-out"],
    paddingLeft: 20,
    paddingRight: 20,
  },
  wipePanelOpen: {
    maxHeight: 160,
    opacity: 1,
    paddingBottom: 20,
  },
  wipeRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
  },
});
