import * as stylex from "@stylexjs/stylex";
import { tokens } from "../lib/tokens.stylex";

export const optionsTableStyles = stylex.create({
  paneTable: {
    maxWidth: 960,
  },
  toolbar: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
  },
  toolbarSpacer: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "auto",
  },
  input: {
    boxSizing: "border-box",
    height: 36,
    minWidth: 0,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens["--xb-border"],
    borderRadius: 10,
    backgroundColor: tokens["--xb-surface"],
    color: tokens["--xb-ink"],
    paddingLeft: 12,
    paddingRight: 12,
    fontSize: 13,
    outline: {
      ":focus-visible": `2px solid ${tokens["--xb-primary"]}`,
    },
    outlineOffset: {
      ":focus-visible": 2,
    },
  },
  inputInvalid: {
    borderColor: tokens["--xb-danger"],
  },
  fieldCaption: {
    margin: 0,
    marginTop: 6,
    fontSize: 11,
    fontWeight: 500,
    color: tokens["--xb-ink-muted"],
  },
  fieldCaptionDanger: {
    color: tokens["--xb-danger"],
  },
  btn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    height: 36,
    paddingLeft: 14,
    paddingRight: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "transparent",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    whiteSpace: "nowrap",
    transitionProperty: "background-color, filter, transform",
    transitionDuration: "150ms",
    transitionTimingFunction: "ease",
    outline: {
      ":focus-visible": `2px solid ${tokens["--xb-primary"]}`,
    },
    outlineOffset: {
      ":focus-visible": 2,
    },
    transform: {
      ":active": "scale(0.96)",
    },
    opacity: {
      ":disabled": 0.45,
    },
  },
  btnPrimary: {
    backgroundColor: tokens["--xb-primary-btn-bg"],
    color: "white",
  },
  btnSecondary: {
    backgroundColor: "transparent",
    borderColor: tokens["--xb-border"],
    color: tokens["--xb-ink"],
  },
  btnDanger: {
    backgroundColor: tokens["--xb-danger"],
    color: "white",
  },
  chipGroup: {
    display: "inline-flex",
    gap: 4,
    padding: 2,
    borderRadius: 10,
    backgroundColor: tokens["--xb-track"],
  },
  chip: {
    height: 28,
    paddingLeft: 10,
    paddingRight: 10,
    borderStyle: "none",
    borderRadius: 8,
    backgroundColor: "transparent",
    color: tokens["--xb-ink-muted"],
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    transitionProperty: "background-color, color",
    transitionDuration: "150ms",
    transitionTimingFunction: "ease",
    outline: {
      ":focus-visible": `2px solid ${tokens["--xb-primary"]}`,
    },
    outlineOffset: {
      ":focus-visible": 2,
    },
  },
  chipActive: {
    backgroundColor: tokens["--xb-surface"],
    color: tokens["--xb-ink"],
  },
  table: {
    width: "100%",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens["--xb-border"],
    borderRadius: 16,
    overflow: "hidden",
  },
  tableHead: {
    display: "grid",
    alignItems: "center",
    gap: 12,
    paddingLeft: 16,
    paddingRight: 16,
    height: 36,
    backgroundColor: tokens["--xb-elevated"],
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens["--xb-border"],
    fontSize: 11,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    color: tokens["--xb-ink-muted"],
  },
  tableRow: {
    display: "grid",
    alignItems: "center",
    gap: 12,
    paddingLeft: 16,
    paddingRight: 16,
    height: 40,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens["--xb-border"],
    fontSize: 13,
    backgroundColor: {
      default: "transparent",
      ":hover": tokens["--xb-track"],
    },
    outline: {
      ":focus-visible": `2px solid ${tokens["--xb-primary"]}`,
    },
    outlineOffset: {
      ":focus-visible": -2,
    },
  },
  tableRowLast: {
    borderBottomStyle: "none",
  },
  cellHandle: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  cellAction: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
  },
  cellWhen: {
    fontVariantNumeric: "tabular-nums",
    color: tokens["--xb-ink-muted"],
  },
  toneDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    flexShrink: 0,
  },
  toneDotDanger: {
    backgroundColor: tokens["--xb-danger"],
  },
  toneDotWarning: {
    backgroundColor: tokens["--xb-warning"],
  },
  syncDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    flexShrink: 0,
  },
  syncDotSynced: {
    backgroundColor: tokens["--xb-success"],
  },
  syncDotPending: {
    backgroundColor: tokens["--xb-warning"],
  },
  syncDotLocal: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens["--xb-ink-muted"],
  },
  tag: {
    height: 18,
    paddingLeft: 6,
    paddingRight: 6,
    borderRadius: 6,
    backgroundColor: tokens["--xb-track"],
    color: tokens["--xb-ink-muted"],
    fontSize: 11,
    fontWeight: 600,
  },
  ghostIcon: {
    display: "grid",
    placeItems: "center",
    width: 28,
    height: 28,
    borderStyle: "none",
    borderRadius: 8,
    backgroundColor: {
      default: "transparent",
      ":hover": tokens["--xb-track"],
    },
    color: {
      default: tokens["--xb-ink-muted"],
      ":hover": tokens["--xb-danger"],
    },
    cursor: "pointer",
    opacity: 0,
    transitionProperty: "opacity, background-color, color",
    transitionDuration: "150ms",
    transitionTimingFunction: "ease",
    outline: {
      ":focus-visible": `2px solid ${tokens["--xb-primary"]}`,
    },
    outlineOffset: {
      ":focus-visible": 2,
    },
  },
  ghostIconVisible: {
    opacity: 1,
  },
  ghostIconConfirming: {
    opacity: 1,
    width: "auto",
    paddingLeft: 10,
    paddingRight: 10,
    color: tokens["--xb-danger"],
    fontSize: 11,
    fontWeight: 700,
  },
  tableScroll: {
    position: "relative",
    maxHeight: 560,
    overflowY: "auto",
  },
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
    fontSize: 12,
    fontWeight: 500,
    color: tokens["--xb-ink-muted"],
  },
  tabular: {
    fontVariantNumeric: "tabular-nums",
    color: tokens["--xb-ink"],
    fontWeight: 600,
  },
  jumpTop: {
    height: 36,
    paddingLeft: 12,
    paddingRight: 12,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens["--xb-border"],
    borderRadius: 10,
    backgroundColor: tokens["--xb-elevated"],
    color: tokens["--xb-ink"],
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    outline: {
      ":focus-visible": `2px solid ${tokens["--xb-primary"]}`,
    },
    outlineOffset: {
      ":focus-visible": 2,
    },
  },
});
