// Configuration object for topics
const topicsConfig = [
	//{
	//	topic: "politics",
	//	description: "posts about political subjects",
	//	threshold: 0.8,
	//},
	{
		topic: "negativity",
		description: "posts with overly negative sentiment",
		threshold: 0.9,
	},
	{
		topic: "sexual_content",
		description: "posts containing pornographic or explicit sexual content",
		threshold: 0.75,
	},
	{
		topic: "china_propaganda",
		description: "posts containing propaganda related to China",
		threshold: 0.65,
	},
	{
		topic: "russian_language",
		description: "posts in Russian language",
		threshold: 1.0, // Set to 1.0 to effectively hide all Russian language posts
	},
	{
		topic: "toxic_content",
		description: "posts with toxic or harmful content",
		threshold: 0.8,
	},
	//{
		//topic: "eyebait",
		//description: "posts designed to attract attention without substance",
		//threshold: 0.6,
	//},
	//{
	//	topic: "promoted_content",
	//	description: "posts promoted by X itself",
	//	threshold: 1.0, // Set to 1.0 to effectively hide all promoted posts
	//},
	//{
	//	topic: "misinformation",
	//	description: "posts containing false or misleading information",
		//threshold: 0.75,
	//},
	{
		topic: "hate_speech",
		description: "posts containing hate speech or discriminatory content",
		threshold: 0.8,
	},
	{
		topic: "conspiracy_theories",
		description: "posts promoting unfounded conspiracy theories",
		threshold: 0.7,
	},
	{
		topic: "spam",
		description: "posts that are spam or unwanted commercial content",
		threshold: 0.85,
	},
	{
		topic: "violence",
		description: "posts containing violent content or inciting violence",
		threshold: 0.8,
	},

	//{
	//	topic: "drug_related",
	//	description: "posts promoting illegal drug use or trade",
	//	threshold: 0.75,
	//},
	//{
	//	topic: "copyright_infringement",
	//	description: "posts potentially infringing on copyrights",
	//	threshold: 0.7,
	//},
	{
		topic: "doxxing",
		description: "posts revealing private or identifying information about individuals",
		threshold: 0.9,
	},
	{
		topic: "bot_activity",
		description: "posts likely generated by bots or automated accounts",
		threshold: 0.8,
	},
	// New topic added to filter low-quality content
	{
		topic: "low_quality_content",
		description: "posts that are low-quality, spammy, or have little informative value",
		threshold: 0.75,
	},
];

// Initial list of noisy and eyebait keywords
const initialKeywords = [
	"SHOCKING",
	"YOU WON'T BELIEVE",
	"MUST SEE",
	"VIRAL",
	"INSANE",
	"MIND-BLOWING",
	"UNBELIEVABLE",
	"BREAKING",
	"EXCLUSIVE",
	"SECRET",
	"MIRACLE",
	"INSTANT",
	"EXPOSED",
	"OUTRAGEOUS",
	"JAW-DROPPING",
	"Promoted",
	"Sponsored",
	// Chinese keywords and phrases related to exaggerated language learning claims
	"背了", "口语", "牛了", "一夜暴富", "速成", "快速提高",
	"立即见", "秘诀", "神奇方法", "轻松学会", "突破瓶颈",
	"零基础", "母语水平", "一键掌握", "效果显著", "革命性突破",
	"超强记忆", "过目不忘", "学习捷径", "语言天才", "完美发音",
	"瞬间提升", "无师自通", "终极秘籍", "语言大师", "口语飞跃",
	"惊人进步", "语言奇迹", "学习神器", "一劳永逸"
];

// Function to perform more advanced NLP-based filtering
function advancedChineseFilter(text) {
	// Convert traditional Chinese characters to simplified
	const simplifiedText = text.replace(/[\u2E80-\u2FD5\u3190-\u319f\u3400-\u4DBF\u4E00-\u9FCC\uF900-\uFAAD]/g, 
		char => traditionalToSimplified[char] || char);
	
	// Tokenize the text (simple word segmentation)
	const tokens = simplifiedText.match(/\b\w+\b|[\u4e00-\u9fa5]+/g) || [];
	
	// Check for keyword matches, including partial matches for Chinese characters
	return initialKeywords.some(keyword => 
		tokens.some(token => token.includes(keyword) || keyword.includes(token))
	);
}

// Simple dictionary for traditional to simplified Chinese conversion
const traditionalToSimplified = {
	'學': '学', '習': '习', '語': '语', '說': '说', '話': '话',
	'發': '发', '音': '音', '記': '记', '憶': '忆', '課': '课',
	'程': '程', '單': '单', '詞': '词', '壹': '一', '貳': '二',
	'參': '三', '肆': '四', '伍': '五', '陸': '六', '柒': '七',
	'捌': '八', '玖': '九', '拾': '十', '佰': '百', '仟': '千',
	'萬': '万', '億': '亿'
	// Add more mappings as needed
};

// Function to check for new posts on the page
async function checkForNewPosts() {
	// Early check for API key
	const apiKey = await getGroqApiKey();
	if (!apiKey) {
		console.error("No API key provided. Aborting analysis.");
		return;
	}

	const posts = document.querySelectorAll('[data-testid="cellInnerDiv"]');

	posts.forEach(async (post) => {
		const tweetArticle = post.querySelector('article[data-testid="tweet"]');
		if (!tweetArticle) return;

		const postId = Array.from(tweetArticle.querySelectorAll("a"))
			.find((a) => a.href.includes("/status/"))
			?.href.split("/")
			.find((part, index, array) => array[index - 1] === "status");
		const postTextElement = tweetArticle.querySelector(
			'[data-testid="tweetText"]',
		);
		const postText = postTextElement ? postTextElement.innerText.trim() : "";

		// Check if the post is promoted
		const isPromoted =
			post.querySelector('[data-testid="promoted-icon"]') !== null;

		if (postId) {
			let analysis = await getCachedAnalysis(postId);
			if (!analysis) {
				analysis = await analyzeTweet(postText, apiKey);
				await cacheAnalysis(postId, analysis);
			}
			applyPostVisibility(
				postId,
				analysis,
				postText,
				initialKeywords,
				isPromoted,
			);
		}
	});
}

// Function to get cached analysis
async function getCachedAnalysis(postId) {
	return new Promise((resolve) => {
		chrome.storage.local.get([`analysis_${postId}`], (result) => {
			resolve(result[`analysis_${postId}`] || null);
		});
	});
}

// Function to cache analysis
async function cacheAnalysis(postId, analysis) {
	return new Promise((resolve) => {
		chrome.storage.local.set({ [`analysis_${postId}`]: analysis }, resolve);
	});
}

// Control variable to enable or disable the hiding feature
const enableHidingFeature = true; // Set to false to turn off the hiding feature

// Function to apply post visibility based on analysis and keywords
function applyPostVisibility(
	postId,
	analysis,
	postText,
	keywords,
	isPromoted,
) {
	if (typeof analysis === "object" && analysis !== null) {
		const shouldHideByTopic = topicsConfig.some(
			(topic) =>
				topic.topic in analysis && analysis[topic.topic] > topic.threshold,
		);

		const shouldHideByKeywords = keywords.some((word) =>
			postText.toLowerCase().includes(word.toLowerCase()),
		);

		const shouldHide =
			shouldHideByTopic ||
			shouldHideByKeywords ||
			isPromoted;

		const postElement = findPostElement(postId);
		if (postElement) {
			if (shouldHide && enableHidingFeature) {
				// Hide the post by creating a placeholder
				createPlaceholder(postElement, postId);
				logHiddenPost(
					postId,
					postElement,
					analysis,
					shouldHideByKeywords,
					isPromoted,
				);
			} else if (postElement.dataset.originalContent) {
				restoreOriginalContent(postElement, postId);
			} else {
				highlightKeywords(postElement);
			}
		} else {
			console.log(`Could not find element for post ${postId} to modify`);
		}
	} else {
		console.log(`Skipping post ${postId} due to invalid analysis result`);
	}
}

// Function to create a placeholder over the post
function createPlaceholder(postElement, postId) {
	// Check if the placeholder already exists
	let placeholder = postElement.querySelector('.hidden-post-placeholder');
	if (!placeholder) {
		// Create the overlay container
		placeholder = document.createElement('div');
		placeholder.className = 'hidden-post-placeholder';
		placeholder.style.cssText = `
			position: absolute;
			top: 0;
			left: 0;
			width: 100%;
			height: 100%;
			background-color: rgba(247, 249, 249, 0.97); /* Slightly transparent to hint at underlying content */
			display: flex;
			flex-direction: column;
			justify-content: center;
			align-items: center;
			z-index: 10;
			pointer-events: all;
		`;

		const message = document.createElement('div');
		message.style.cssText = `
			color: #657786;
			font-size: 15px;
			line-height: 20px;
			text-align: center;
			padding: 0 10px;
		`;
		message.textContent = 'This post has been hidden based on your filter settings.';
		placeholder.appendChild(message);

		const revealButton = document.createElement('button');
		revealButton.textContent = 'Reveal Post';
		revealButton.style.cssText = `
			background-color: #1DA1F2;
			color: #FFFFFF;
			border: none;
			border-radius: 9999px;
			padding: 8px 16px;
			margin-top: 12px;
			cursor: pointer;
			font-size: 14px;
			font-weight: bold;
			font-family: 'Segoe UI', Arial, sans-serif;
		`;
		revealButton.onmouseover = () => {
			revealButton.style.backgroundColor = '#0d95e8';
		};
		revealButton.onmouseout = () => {
			revealButton.style.backgroundColor = '#1DA1F2';
		};
		revealButton.onclick = () => restoreOriginalContent(postElement, postId);

		// Center the button
		const buttonContainer = document.createElement('div');
		buttonContainer.style.cssText = 'display: flex; justify-content: center;';
		buttonContainer.appendChild(revealButton);
		placeholder.appendChild(buttonContainer);

		// Ensure the post element is positioned relatively
		postElement.style.position = 'relative';

		// Append the placeholder overlay to the post element
		postElement.appendChild(placeholder);

		// Add the 'hidden' class to the post
		postElement.classList.add('post-hidden');
	} else {
		placeholder.style.display = 'flex';
	}
}

// Function to restore the original content of the post
function restoreOriginalContent(postElement, postId) {
	// Remove the placeholder overlay
	const placeholder = postElement.querySelector('.hidden-post-placeholder');
	if (placeholder) {
		placeholder.style.display = 'none';
	}

	// Remove the 'hidden' class from the post
	postElement.classList.remove('post-hidden');

	// Update the hidden posts log
	removeFromHiddenPostsLog(postId);
}

// Function to remove the post from the hidden posts log
function removeFromHiddenPostsLog(postId) {
	const index = hiddenPostsLog.findIndex(log => log.includes(`Post ${postId} hidden`));
	if (index !== -1) {
		hiddenPostsLog.splice(index, 1);
		updateOverlay();
	}
}

// Function to find the div element containing a specific post ID
function findPostElement(postId) {
	if (typeof postId !== "string") {
		throw new Error("postId must be a string");
	}
	const cellInnerDivs = document.querySelectorAll(
		'[data-testid="cellInnerDiv"]',
	);

	for (const div of cellInnerDivs) {
		const link = div.querySelector(`a[href*="/status/${postId}"]`);
		if (link) {
			return div;
		}
	}

	return null; // Return null if no matching element is found
}
window.findPostElement = findPostElement;

// Function to reset the cache (seenPostIds and analysis results)
function resetCache() {
	chrome.storage.local.get(null, (items) => {
		const allKeys = Object.keys(items);
		const analysisKeys = allKeys.filter((key) => key.startsWith("analysis_"));
		chrome.storage.local.remove(analysisKeys, () => {
			console.log("Cache (analysis results) has been reset.");
		});
	});
}

// Make resetCache function available in the global scope
window.resetCache = resetCache;

console.log("To reset the cache, run resetCache() in the console.");

// Function to analyze a tweet using the Groq API
async function analyzeTweet(tweetText, apiKey) {
	let retries = 0;
	const maxRetries = 3;
	const messages = [
		{
			role: "system",
			content: `Your task is to evaluate Tweets/X posts. Always respond in JSON. Use the following format:\n\n{\n${topicsConfig
				.map((topic) => `    "${topic.topic}": 0.0`)
				.join(",\n")}\n}\n\nRate the provided post from 0.0 to 1.0 for each topic based on the descriptions:\n\n${topicsConfig
				.map((topic) => `${topic.topic}: ${topic.description}`)
				.join("\n")}`,
		},
		{
			role: "user",
			content: tweetText,
		},
	];

	while (retries < maxRetries) {
		try {
			const response = await fetch(
				"https://api.groq.com/openai/v1/chat/completions",
				{
					method: "POST",
					headers: {
						"Content-Type": "application/json",
						Authorization: `Bearer ${apiKey}`,
					},
					body: JSON.stringify({
						messages: messages,
						model: "llama-3.1-8b-instant",
						temperature: 1,
						max_tokens: 1024,
						top_p: 1,
						stream: false,
						response_format: {
							type: "json_object",
						},
						stop: null,
					}),
				},
			);

			if (!response.ok) {
				throw new Error(`HTTP error! status: ${response.status}`);
			}

			const data = await response.json();
			if (!data.choices || !data.choices[0] || !data.choices[0].message || !data.choices[0].message.content) {
				throw new Error("Invalid response structure from Groq API");
			}

			return JSON.parse(data.choices[0].message.content);
		} catch (error) {
			console.error(`Attempt ${retries + 1} failed:`, error);
			retries++;
			if (retries === maxRetries) {
				console.error("Max retries reached. Returning default analysis.");
				return topicsConfig.reduce((acc, topic) => {
					acc[topic.topic] = 0;
					return acc;
				}, {});
			}
			await new Promise(resolve => setTimeout(resolve, 1000 * retries));
		}
	}

	return {};
}

// Function to get or set the Groq API key
async function getGroqApiKey() {
	return new Promise((resolve) => {
		chrome.storage.local.get(["GROQ_API_KEY"], (result) => {
			if (result.GROQ_API_KEY) {
				resolve(result.GROQ_API_KEY);
			} else {
				const apiKey = prompt("Please enter your Groq API key:");
				if (apiKey) {
					chrome.storage.local.set({ GROQ_API_KEY: apiKey }, () => {
						resolve(apiKey);
					});
				} else {
					resolve(null);
				}
			}
		});
	});
}

// Debounce function to limit how often the scroll event fires
function debounce(func, delay) {
	let timeoutId;
	return function (...args) {
		clearTimeout(timeoutId);
		timeoutId = setTimeout(() => func.apply(this, args), delay);
	};
}

// Create debounced version of checkForNewPosts
const debouncedCheck = debounce(checkForNewPosts, 300);

// Modify the scroll event listener to call checkForNewPosts
window.addEventListener("scroll", () => {
	if (window.location.hostname === "x.com") {
		debouncedCheck();
	}
});

// Initial check when the page loads
if (window.location.hostname === "x.com") {
	checkForNewPosts();
}

// Add this new configuration object for keyword highlighting
const keywordHighlights = [
  { category: 'AI', color: '#FFD700', keywords: ['llm', 'transformer', 'neural network', 'deep learning', 'machine learning', 'ai'] },
  { category: 'Math', color: '#00CED1', keywords: ['algebra', 'calculus', 'topology', 'linear algebra', 'statistics', 'probability'] },
  { category: 'CS', color: '#FF69B4', keywords: ['algorithm', 'data structure', 'complexity', 'compiler', 'operating system', 'database'] },
  { category: 'Core Concepts', color: '#32CD32', keywords: ['recursion', 'abstraction', 'optimization', 'parallelism', 'concurrency', 'encryption'] }
];

// Add this new function to highlight keywords
function highlightKeywords(postElement) {
  const tweetTextElement = postElement.querySelector('[data-testid="tweetText"]');
  if (!tweetTextElement) return;

  const originalText = tweetTextElement.innerHTML;
  let highlightedText = originalText;

  keywordHighlights.forEach(({ category, color, keywords }) => {
    keywords.forEach(keyword => {
      const regex = new RegExp(`\\b${keyword}\\b`, 'gi');
      highlightedText = highlightedText.replace(regex, `<span style="background-color: ${color}; padding: 2px; border-radius: 3px;" title="${category}">${keyword}</span>`);
    });
  });

  if (highlightedText !== originalText) {
    tweetTextElement.innerHTML = highlightedText;
  }
}
